_target_: src.datamodule.QoSGNNWSDreamDatamodule.QoSGNNWSDreamDatamodule

qos: "rt"
u_fanouts: [5, 25]
s_fanouts: [20, 45]
batch_size: 1024
density: 0.025
raw_dir: null
force_reload: false
verbose: false
transform: null